FORMAT: 1A

# Simple Recipe Manager
The Simple Recipe Manager API is a *recipe storage* service similar what you'd find in your cookbook, at home, but should meet the needs of even the most busy kitchens. It also aims to make aggregating a group of recipes easy, and building *shopping lists* easy.

# Group Recipe
The base unit of a *recipe*. You'll be consuming pieices of this in client apps.

## Recipe [/recipes/{id}]
A single recipe object.

The Recipe object has the following attributes:

- oven_fan
- oven_temp
- amount
- unit
- oven_time
- ingredients
    - ingredient
        - amounts
            - amount
            - unit
        - processing
        - notes
        - substituions
        - usda_num
- source_book
    - authors
    - title
    - isbn
    - notes
- source_authors
- steps
    - step
        - haccp
            - control_point
            - critical_control_point
    - notes
- yeilds
    - yield
        - amount
        - unit
- recipe_uuid
- recipe_name
- X-prep_time
- X-added_at
- X-description
- X-default_image_url

The *recipe_uuid* and *added_at* property are assigned by the API when saved.

+ Parameters
    + id (String) ... ID fo the recipe to get

+ Model (application/json)

    JSON representation of a recipe resource.    

    + Body
    
            {
                "recipe_uuid" : "c0c11bc6-fa00-4239-845e-66192f8f93fe",
                "added_at" : 1234568203,
                "prep_time" : 0,
                "cooking_time" : 5,
                "recipe_name" : "Cookies"
                
            }

### Retrieve a single Recipe [GET]
+ Response 200

    [Recipe][]
    
### Edit a recipe [PUT]
+ Request (application/json)

        {
            "recipe_uuid" : "c0c11bc6-fa00-4239-845e-66192f8f93fe",
            "recipe_name" : "Chocolate chip cookies"
        }
    
+ Response 200

    [Recipe][]