FROM dockerfile/java

RUN mkdir /app
ADD https://s3.amazonaws.com/travis-build-artifacts/travis-srm-api/target/JAR_NAME.jar /app/server.jar

CMD ["java", "-jar", "/app/server.jar", "server" ]

EXPOSE 8080 8081
